# Generated by Django 2.1.2 on 2018-10-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogpost',
            new_name='Post',
        ),
    ]
